services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: containers_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: containers
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    cpus: "1.0"
    mem_limit: "512m"

volumes:
  postgres_data:
