services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: containers_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: containers
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    cpus: "1.0"
    mem_limit: "512m"

  api:
    image: api
    container_name: api
    restart: unless-stopped
    env_file:
      - ./apps/api/.env.local
    ports:
      - "9999:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
    cpus: "1.0"
    mem_limit: "512m"

  web:
    image: web
    container_name: web
    restart: unless-stopped
    env_file:
      - ./apps/web/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api
    cpus: "1.0"
    mem_limit: "512m"

volumes:
  postgres_data:
