services:
  traefik:
    image: traefik:v3.6.7
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80

    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  database:
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: containers
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    cpus: "1.0"
    mem_limit: "512m"
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    env_file:
      - ./apps/api/.env.prod
    expose:
      - "9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - api_uploads:/data/uploads
    depends_on:
      - database
    cpus: "1.0"
    mem_limit: "512m"
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.paper.sh`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=9999
      - traefik.docker.network=proxy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    env_file:
      - ./apps/web/.env.prod
    expose:
      - "3000"
    depends_on:
      - api
    cpus: "1.0"
    mem_limit: "512m"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`app.paper.sh`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.services.web.loadbalancer.server.port=3000

volumes:
  postgres_data:
  api_uploads:

networks:
  proxy:
    external: true
  internal:
    driver: bridge
